# Generated by Django 4.2.4 on 2023-09-16 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amount",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_amounts",
                to="api.recipe",
                verbose_name="Рецепт",
            ),
        ),
    ]
