# Generated by Django 4.2.4 on 2023-09-20 20:30

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_amount_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amount",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        240, message="Максимальное количество ингредиентов 20"
                    ),
                    django.core.validators.MinValueValidator(
                        1, message="Минимальное количество ингредиентов 1"
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        240, message="Максимальное время 240 мин"
                    ),
                    django.core.validators.MinValueValidator(
                        1, message="Минимальное время 1 мин"
                    ),
                ],
                verbose_name="Время приготовления в минутах",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                samples=None,
                unique=True,
                verbose_name="Цвет",
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                check=models.Q(("user", models.F("author")), _negated=True),
                name="is_not_following",
            ),
        ),
    ]
