# Generated by Django 4.2.4 on 2023-09-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_recipe_options_recipe_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="text",
            field=models.TextField(unique=True, verbose_name="Рецепт"),
        ),
    ]
