version: '3.3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.4
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    image: gennadyumikashvili/foodgram_backend
    env_file: .env
    ports:
      - "8080:8000"
    volumes:

      - static_volume:/api/static/
      - media_volume:/api/media
    depends_on:
      - db

  frontend:
    image: gennadyumikashvili/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/api/static/
      - media_volume:/api/media
    depends_on:
      - backend

