version: '3.3'
services:
  db:
    image: postgres:13.4
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  frontend:
    image: gennadyumikashvili/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../api/docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/api/static/
      - media_volume:/api/media
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8000"
    volumes:
      - ../backend:/api
      - static_volume:/api/static/
      - media_volume:/api/media
volumes:
  static_volume:
  media_volume:
  postgres_data: